In [1]:
import numpy as np
import pandas as pd

print(np.__version__)
print(pd.__version__)

2.5.2
3.0.5


In [2]:
v1 = np.array([10,6,7])
v2 = np.array([3,5,12])
v3 = np.array(5)
print(v1.shape)

(3,)


In [5]:
class Student:
    def __init__(self,name,age)->None:
        self._name =name 
        self._age= age 
    @property
    def name (self):
        return f"{self._name}"    

In [6]:
s1 = Student("Shahd",21)
s1.name 

'Shahd'

In [7]:
vec = np.array([1,2,3,4,5,6])
mat=vec.reshape((2,3))
print(mat)

[[1 2 3]
 [4 5 6]]


In [8]:
vec = np.array([1,2,3,4])
vec.shape[0]

4

In [9]:
def array_reshap(arr,row = -1,cols= -1):
    try:
        arr = np.array(arr)
        return arr.reshape((row, cols))
    except Exception as e :
        raise ValueError("Invalid Reshape operation:{e}")    

In [11]:
vec = [1,2,3,4,5,6]
print ("test 1(2*3 matrix):",array_reshap(vec,2,3))

test 1(2*3 matrix): [[1 2 3]
 [4 5 6]]


In [13]:
import numpy as np

In [14]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [18]:
class Student:
    def __init__(self,name):
        self.__name = name

In [ ]:
s1 = Student("Shahd")

s1._Student__name # دي طريقه علشان اجيب الحاججه الرابفت

'Shahd'

In [22]:
s1.__dict__

{'_Student__name': 'Shahd'}

In [ ]:
# private 
class Student :
    def __init__(self,name):
        self.__name =name
    @property
    def name(self):
        return self.__name 
    @name.setter # هحط قيمه للبرايفتت
    def name(self,value):
         self.__name = value       

In [35]:
s1 = Student("shahd")
s1.name = "shahd"
s1.name

'shahd'

In [39]:
vec = np.linspace(0,10,num =25)
mat = vec.reshape(5,5)
mat

array([[ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667],
       [ 2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ],
       [ 4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333],
       [ 6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667],
       [ 8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ]])

In [40]:
I = np.identity(3,dtype='float64')
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
np.random.random((3,3))

array([[0.24909617, 0.93197256, 0.9079397 ],
       [0.11664998, 0.7715207 , 0.33532357],
       [0.32500437, 0.02370383, 0.44581696]])

In [ ]:
np.random.randint(0,11,(5,5)) # randint => ارقام صحيحه

array([[ 6,  2,  0,  7,  3],
       [ 1, 10,  1,  3,  9],
       [ 4,  0,  2, 10,  3],
       [ 2,  0,  8,  3,  5],
       [ 1,  4,  9,  7, 10]], dtype=int32)

In [45]:
a =['Shahd','Omar','Ali']
np.random.choice(a,size=(3,4))

array([['Shahd', 'Omar', 'Ali', 'Shahd'],
       ['Shahd', 'Ali', 'Omar', 'Ali'],
       ['Shahd', 'Omar', 'Ali', 'Shahd']], dtype='<U5')

In [48]:
mat1 = np.ones((3,4))

mat2 = np.zeros((5,3))
np.savez('file_test.npz',ones_mat= mat1,zeros_mat= mat2)

In [49]:
with np.load('file_test.npz') as file:
    mat1 = file['ones_mat']
    mat2 = file['zeros_mat']

In [50]:
print(mat1)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [51]:
print(mat2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [55]:
m1 = np.array([[1, 2, 3],
                    [0, 0, 0]])

m2 = np.array([[5, 6, 7],
[1, 1, 7]])    
mat3 = np.vstack((m1,m2)) 
mat3               

array([[1, 2, 3],
       [0, 0, 0],
       [5, 6, 7],
       [1, 1, 7]])

In [ ]:
s = 4
v = np.array([2,4,3,4,10])
#v == s 
v.__eq__(s)
v.__It__

array([False,  True, False,  True, False])

In [62]:
class Student:
   def __init__(self,name):
    self.name =name

    def __eq__(self,value :object):
        pass 



In [ ]:
# مهم
s1 = Student("Shahd")
s2 = Student("Shahd")
s1 == s2

False

In [ ]:
v = np.array([1,3,4,5,0])
np.all(v>1)

np.False_

In [66]:
v = np.array([1,3,4,5,0])
np.any(v>1)

np.True_

In [68]:
v1 = np.array([1, 2, 3, 4, 5])
v2 = np.array([2, 3, 0,5 ,3])
np.isclose(v1,v2,atol= 1 )

array([ True,  True, False,  True, False])

In [69]:
v1 = np.array([1, 2, 3, 4, 5])
v2 = np.array([2, 3, 0,5 ,3])
np.allclose(v1,v2,atol= 1 )

False

In [ ]:
v = np.array([2, 4, 3 ,4 ,10])
condition = v>=4
new_array = np.where(condition ,-1,v) #==v[condition]= -1
print(new_array)

[ 2 -1  3 -1 -1]


In [77]:
v = np.array([1 ,2 ,3 ])
c =2
sumation = v + c 
multi = v * c
print(sumation)
print(multi)

[3 4 5]
[2 4 6]


In [78]:
mat1 = np.array([[1,2,3],
                  [4,5,6] ,
                  [7,8,9]  ])
v22 = np.array([.5,.5,.1])     
matrix = mat1 * v22
print(matrix)             

[[0.5 1.  0.3]
 [2.  2.5 0.6]
 [3.5 4.  0.9]]


In [82]:
import numpy as np
from scipy.sparse import csr_matrix ,csc_matrix

mat = np.array([
    [1, 0, 0, 1, 0, 0],
    [0, 2, 0, 0, 0, 0],
    [0, 0, 0, 2, 0, 0]
])

smat = csc_matrix(mat)

smat

<Compressed Sparse Column sparse matrix of dtype 'int64'
	with 4 stored elements and shape (3, 6)>

   ---------------------------------------- 0.0/36.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/36.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/36.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/36.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.6 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.6 MB ? eta -:--:--
    --------------------------------------- 0.5/36.6 MB 493.7 kB/s eta 0:01:14
    --------------------------------------- 0.5/36.6 MB 493.7 kB/s eta 0:01:14
    --------------------------------------- 0.8/36.6 MB 589.1 kB/s eta 0:01:01
   - -------------------------------------- 1.0/36.6 MB 729.5 kB/s eta 0:00:49
   - -------------------------------------- 1.3/36.6 MB 721.7 kB/s eta 0:00:49
   - -------------------------------------- 1.3/36.6 MB 721.7 kB/s eta 0:00:49
   - -------------------------------------- 1.6/36.6 MB 729.4 kB/s eta 0:00:49
   -- ---------------------